export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOG_OUT = "LOG_OUT"
export const LOAD_PROFILE = "LOAD_PROFILE"

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS"
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL"
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST"

export const SELECT_VIDEOS_SUCCESS = "SELECT_VIDEOS_SUCCESS"
export const SELECT_VIDEOS_FAIL = "SELECT_VIDEOS_FAIL"
export const SELECT_VIDEOS_REQUEST = "SELECT_VIDEOS_REQUEST"

export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL"
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST"

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS"

export const COMMENT_VIDEO_SUCCESS = "COMMENT_VIDEO_SUCCESS"
export const COMMENT_VIDEO_FAIL = "COMMENT_VIDEO_FAIL"
export const COMMENT_VIDEO_REQUEST = "COMMENT_VIDEO_REQUEST"

export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL"

export const RELATED_VIDEOS_SUCCESS = "RELATED_VIDEOS_SUCCESS"
export const RELATED_VIDEOS_FAIL = "RELATED_VIDEOS_FAIL"
export const RELATED_VIDEOS_REQUEST = "RELATED_VIDEOS_REQUEST"

export const SEARCH_VIDEOS_SUCCESS = "SEARCH_VIDEOS_SUCCESS"
export const SEARCH_VIDEOS_FAIL = "SEARCH_VIDEOS_FAIL"
export const SEARCH_VIDEOS_REQUEST = "SEARCH_VIDEOS_REQUEST"


